### ISSUE TITLE
Shared branch

### ISSUE THREAD

**Issue by ItamarShDev** [Dor-H/hello-git#1]
What is this branch goal?

**Comment by Dor-H** [comment]
@ItamarShDev  Sorry but I don't understand the question...

**Comment by ItamarShDev** [comment]
you have an extra branch named "shared"
this branch, according to git-immersion does not suppose to exist, looking at the name - i guess it was supposed to be part of "git remote add **shared**"?

**Comment by Dor-H** [comment]
I followed all the 53 steps, Maybe I played with it later but I don't really remember... it was a month ago.

**Comment by ItamarShDev** [comment]
ok, just wanted to know :+1:
